/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 */


/* Generated By:JJTree: Do not edit this line. JDMHost.java */

package com.sun.jmx.snmp.IPAcl;


class JDMHost extends SimpleNode {

  JDMHost(int id) {
    super(id);
  }

  JDMHost(Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JDMHost(id);
  }

  public static Node jjtCreate(Parser p, int id) {
      return new JDMHost(p, id);
  }


}
