/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 */


/* Generated By:JJTree: Do not edit this line. JDMManagers.java */

package com.sun.jmx.snmp.IPAcl;

class JDMManagers extends SimpleNode {
  JDMManagers(int id) {
    super(id);
  }

  JDMManagers(Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JDMManagers(id);
  }

  public static Node jjtCreate(Parser p, int id) {
      return new JDMManagers(p, id);
  }
}
